[package]
name = "parity-der"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "MIT/Apache 2.0"

[dependencies]
libc = "0.2.68"
webpki = "0.21.2"

[dev-dependencies]
ring = "0.16.11"
untrusted = "0.7.0"
