blank_lines_upper_bound = 1
condense_wildcard_suffixes = true
edition = "2018"
error_on_line_overflow = true
error_on_unformatted = true
fn_args_layout = "Compressed"
fn_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
# hard_tabs = true
match_arm_blocks = false
match_block_trailing_comma = true
max_width = 100
merge_imports = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
reorder_imports = true
trailing_comma = "Vertical"
trailing_semicolon = false
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
wrap_comments = true
